### ISSUE TITLE
ResizeObserver polyfill, and render-prop idea

### ISSUE THREAD

**Issue by ZeeCoder** [radubrehar/resize-observer#1]
Hey @radubrehar ,

Love the idea, I was actually about to do something similar myself.
Two things I would like to discuss though:
1) I think you would benefit from mentioning existing polyfills, with which this lib can be used in most browsers: https://github.com/que-etc/resize-observer-polyfill
1) Why not use a render-prop? I think this would be incredible useful:
```js
import React from 'react';
import { render } from 'react-dom';

import ResizeObserver from '@rb/resize-observer';

const App = () => {
  return (
    <ResizeObserver render=(({ width, height }) => {
          console.log({ width, height });

          // Observing the element returned here 
          return (
            <div style={{ width: '50vw', border: '1px solid red' }}>
              This element has width: 50vw, so resize the browser window to get
              notifications in the console
            </div>
          );
    }) />
  );
};

render(<App />, document.getElementById('root'));
```
☝ That would allow you to render based on component size too.

**Comment by radubrehar** [comment]
1. Sounds great, I was about to do that
2. A great idea, but that's another concern and I want to keep this component simple - it should only have one concern. This is a good idea for another component, `<ElementQuery />` which I will implement probably this week. The `ElementQuery` would obviously use `<ResizeObserver />` and have the `render` prop.

What do you think?
Would you mind doing a PR for the `README.md` file to add the mentioned polyfill?

**Comment by ZeeCoder** [comment]
I think it would be still simple, it literally wouldn't do anything more using a render prop as it did as a normal component. 🤔
The only difference is capabilities.

Tbh I would avoid making yet another "ElementQuery" component.
It implies that you do some CSS query thingy, (which you don't) and a lot of people would probably lose interest the moment they read the name.
(Container / Element queries have some bad rep.)

imho making it work as a render-prop is still minimalistic, and does no more than it's supposed to, while giving you an extra feature.

Just imagine if I want to either render a part of the component or not based on the width.
It would be trivial with a render-prop style component, while having it work as it does right now would force me to set the state of the outer component on the resize callback and then do the conditional render.

So much work for something that could be allowed to work out-of-the-box. 😅

**Comment by ZeeCoder** [comment]
I think a render-prop solution would even be simpler implementation-wise too.

**Comment by ZeeCoder** [comment]
not sure where you are with this, but I've implemented the proposed API here:
https://github.com/ZeeCoder/container-query/blob/master/packages/react-container-query/README.md
